### ISSUE TITLE
UI & Wording Feedback 

### ISSUE THREAD

**Issue by julianbauer** [nimiq/hub#182]
# General
- [x] Headline line-height is wrong (is 1, but should be 1.2)
![Screen Shot 2019-03-26 at 10 20 41](https://user-images.githubusercontent.com/4731916/54985293-d5201a00-4fb0-11e9-9405-7e8e6951786c.png)

- [x] The description text below the headline should always keep the same distance to the headline (reduce that spacing to 24px). Together they form a block that's top aligned (reduce spacing between them to 24px). Buttons and info at the bottom form another block that's bottom-aligned, the content in between is usually vertically centered.
![header footer](https://user-images.githubusercontent.com/4731916/54985563-4cee4480-4fb1-11e9-8ee5-f30a44899be1.png)

- [x] "Skip"-button should be moved up around 4px to compensate line-height

- [x] "Skip"-button click area should be taller, but not span the whole width
![Group](https://user-images.githubusercontent.com/4731916/54985126-84a8bc80-4fb0-11e9-8a73-6261ad88d0e5.png)

- [x] Big Button misses hover effect (seems to be overridden), interestingly this doesn't happen on RecoveryWords screens

- [x] 16px text line-height should be exactly 1.3 (Figma messes this up in the code export for some reason)

- [x] coloured intro text below headline is regular but should always be semibold (for contrast)

## Password Box
- [x] If password is wrong: Don't shake inside textfield, but shake the whole box, and more subtle, maybe can become orange or red at the same time. Is there a way to try that out myself?
- [x] If a flow requires a password entry to continue, and the user clicks on the back button in the next step after having successfully entered the password, the password box should stay (right now the password gets saved and the password box is replaced by a button). The reason is that otherwise we would have to introduce a lot of special rules to make those altered screens work well in terms of UX, which wouldn't be economical for this edge-casey behaviour.

## Back Arrow
- [x] We need to change the style of the back arrow, because it's indifferent from the secondary button we have in some screens at the bottom of the modal. This is the new one (14px bold): 
![Screen Shot 2019-03-27 at 17 35 46](https://user-images.githubusercontent.com/4731916/55094619-04b94a00-50b7-11e9-9aba-7e3af6054556.png)
- [x] **Wording**
_Text:_ “Back to Accounts” if coming from Safe

# Onboarding Switch
- [x] **Wording**
_Create Account button:_ “Choose an Avatar. ...”
_Login button:_ “...or Recovery Words.”
_Back button:_
From website: “Back to nimiq.com” 
From safe: “Back to Accounts”

# Signup
- [x] Bug: If in “Confirm password” back arrow is clicked and a new Identicon is chosen, the next step has the headline “Confirm password”, instead of “Create a password”.

## Step 1 (Choose Avatar)
- [x] **Wording**
_Headline:_ “Choose Avatar”
_Generate New button:_ “New Avatars”
_Back button:_ “Back to Join Nimiq”

## Step 2 (Create Password)
- [x] **Wording**
_Headline:_ “Create password”
_Subline:_ “This is your Account with your first Address in it.”
_Enter at least 8 characters versions:_ 
“Enter min. 8 characters”
“Sufficient password”
“Good password”
“Strong password”
_Main CTA_
“Confirm”

## Step 3 (Confirm Password)
- [x] Wording
_Headline:_ “Confirm password”
_Subline:_ “This is your Account with your first Address in it.”
_Blue screen:_ “Connecting to Nimiq”

# Download Login File
### Step 1 (Info)
- [x] **Wording**
_CTA:_ “Create password”

### Step 2 (Set Password)
- [ ] Is it possible to use the original dash size?
- [x] We should have a textblock here explaining that the password will secure the file.
![download_login_file_step 1](https://user-images.githubusercontent.com/4731916/54988262-5af29400-4fb6-11e9-82aa-84c6793a0822.png)
- [x] **Wording**
_Subline:_ “Create a password to protect your Login File.”)

### Step 3 (Repeat Password)
- [ ] Nice to have: Transition from empty login file to Login File: Colored Login File fades in while growing with a bounce easing (similar to first identicon appearing in the AccountRing). Probably needs to be finetuned.

### Step 4 (Download File)
- [ ] ~Nice to have: Animate file from step 2 to step 3 (grow with subtle bounce easing)~
- [ ] File shouldn't be clickable on Desktop – Either file is clickable with respective note (mobile) or button is clickable

### Step 1 (Info)
- [x] **Wording**
_Headline:_ “Save Account” 
_Subline:_ “Your Login File grants access to your Account. Download and save it.” 
“Your Account is stored in your browser’s cache.” 
“It might be deleted automatically or by accident.”
“Download the Login File to save your Account.”
_Text above Button:_ “Keep it safe and confidential.”

### Step 2 (Unlock Login File)
- [x] Headline "Download Login File" --> "Unlock Login File"
- [x] Blurred Login File missing
- [x] **Wording**
_Headline:_ “Unlock Login File”
_Main CTA:_ Continue when the correct password is entered? NO: Find Wording

### Step 3 (Download)
- [x] **Wording**
_Headline:_ “Save Login File” 
_CTA:_ “Download”

# Recovery Words
## Step 1 (Info)
- [x] Add perspective to the flipping animation + switch flip direction (right-edge-to-left, like the page of a book)
- [x] progress bar empty steps have wrong color
![steps color](https://user-images.githubusercontent.com/4731916/55077272-9913b480-5097-11e9-8430-cfa8c0c092b8.png)

- [x] intro text has wrong font size (is: 18px, should be 16px)
- [x] **Wording**
_1)_ “Keep your words offline, enter them nowhere but on keyguard.nimiq.com”

## Step 2 (Show words)
- [x] Top words are already overlayed by gradient shade, also bottom words when scrolled
- [x] numbers should be semibold and aligned with the base-line of the corresponding word
![numbers](https://user-images.githubusercontent.com/4731916/55077330-c52f3580-5097-11e9-94cd-b09b47d3f6a2.png)

- [x] scrollbar should be at the edge of the modal-box
![scrollbar](https://user-images.githubusercontent.com/4731916/55077312-b6488300-5097-11e9-92ba-57f9a8f086e0.png)

- [x] "Skip for now" shouldn't have underline on hover
- [x] **Wording**
_Subline:_ “Anyone with these words can access your Account! Keep them safe.
_CTA:_ “Confirm backup”

## Step 3 (Validate words)
- [x] big number should be semibold
- [x] decrease margin between number and "What is the Xth word" by 8px (to compensate for line-height)
- [x] horizontal spacing between words should be exactly 16px. It's a bit bigger because due to the inline-block layout the space between the elements in the markup is shown in the interface. Solution: remove the space between the elements in the code or use a flex-layout
- [x] shaking word is shaking too much. Animation:
```
@keyframes shake {
    10%, 90% {
        transform: translate3d(-1px, 0, 0);
    }
    
    20%, 80% {
        transform: translate3d(1px, 0, 0);
    }

    30%, 50%, 70% {
        transform: translate3d(-2px, 0, 0);
    }

    40%, 60% {
        transform: translate3d(2px, 0, 0);
    }
}
```

- [ ] ~~Correct word should have a subtle success animation. Animation TBD~~ (https://github.com/nimiq/keyguard/issues/392)
- [x] after clicking a word, shortly a no-interaction cursor shows up, which is weird.
- [x] after clicking a word, correct or not, all words decrease in opacity. It's good if this happens for all uninvolved words, but if the wrong word is clicked, both that and the blinking correct word should stay at 100% opacity. If the right word is being clicked of course only that one stays at 100%
- [x] **Wording**
_Headline:_ “Validate backup” 

# Add Address
- [x] Unlock Screen in Figma (it's a universal unlock screen for the account, so it can be used for recovery words password entry as well)
- [x] if identicon images aren't loaded yet, rectangular outlines appear which overlap. Can we remove them?

## Step 1 (Unlock)
- [x] **Wording**
_Headline:_ “Unlock Account”
_Subline:_ “To add a new Address, please unlock your Account first. 

## Step 2 (Choose Address)
- [x] **Wording**
_Headline:_ “Choose a new Avatar”
_Generate New button:_ “New Avatars”

## Step 3 (Naming overlay)
- [x] **Wording**
_CTA:_ “Add to Account”

## Loading/Success
- [x] **Wording**
_Blue screen:_ “Adding new Address”
_Success Screen:_ “New Address added to your Account.”

# Login 
## with Login File
- [x] Hover/Focus/Drag styles:
![Drag](https://user-images.githubusercontent.com/4731916/55096652-97a7b380-50ba-11e9-8b32-12127b2d1bd4.png)

- [x] "Create new account" doesn't have the right hover effect
- [ ] ~~"Continue" Button is not needed, correct password should unlock directly. Is this possible?~~
- [ ] ~~Lock-opening animation after password is correct is missing. Will provide.~~ (https://github.com/nimiq/keyguard/issues/281)
- [x] **Wording**
_Headline:_ “Create new Account”
_Back button:_ “Back to Accounts”
_Storing your account:_ “Connecting to Nimiq”
_Idea:_ Add steps of what is happening in the background to the blue screen?

### Step 1 (Input Words)
- [x] placeholder numbers in inputs should be semibold, and hidden on focus
- [x] "Press TAB to ..." should be bold
- [x] transitions missing for hover/focus/error states
- [x] filled input has wrong style – see screens
![Frame 5](https://user-images.githubusercontent.com/4731916/55076674-50a7c700-5096-11e9-9eab-87dbce1a0ea7.png)

- [x] error state of input should shake less, see shake animation in word validation
- [x] input border only turns red on error if clicked outside the field, not if tabbed into next field. should become red for both actions.
- [x] "This is not a valid account. Typo?" is 50% transparent. Should be 100% opaque (and bold, as "Press TAB...")
![Screen Shot 2019-03-26 at 15 05 13](https://user-images.githubusercontent.com/4731916/55077410-f3147a00-5097-11e9-8c70-2e8635b5edca.png)

- [x] Shake animation of whole word box is too strong. Use same shake animation as for single inputs

### Step 2 (Create Password)
- [x] password creation can't be skippable in this flow.
- [x] login file placeholder isn't centered
![Group 3](https://user-images.githubusercontent.com/4731916/55076648-3ff75100-5096-11e9-949c-7a81af33975d.png)
 
# Logout
- [x] Line height for image headlines ("Is your Login File...", "Do you know where...") should be 1.4
- [x] **Wording**
_Subline:_ “If you log out without saving your Account, you will irreversible
 lose access to it!”

# Change Password
## Step 1 (Create Password)
- [x] password creation can't be skippable in this flow.
- [x] **Wording**
_2._ “If a Login File was compromised: Please create a new Account and transfer all funds.”
_CTA:_ “Confirm”

## Step 2 (Confirm)
- [x] **Wording**
_Headline:_ “Confirm new password”

## Step 3 (Download LoginFile)
- [x] **Wording**
_Headline:_ “Save your Login File”
_Success Screen:_ “New Login File and password created.”

# Send TX
- [x] amount should be centered if no message is provided
- [x] plain account numbers should be written in Fira Mono
![Group 4](https://user-images.githubusercontent.com/4731916/55077646-8948a000-5098-11e9-961b-9c4a8594ade7.png)

- [x] named addresses shouldn't fade out, but collapse. Also, they should have more room until they collapse. They naming concept is built on the assumption that we have a 148px wide box to display the name.
![naming concept](https://user-images.githubusercontent.com/4731916/55077502-366ee880-5098-11e9-8eea-1adef22bdf36.png)

- [x] Even if I add the receipient as a contact, the name is not shown, but the account number instead. (Also in the detail overlay it still says "unnamed contact")

## Account Detail Overlay
- [ ] Blur entry animation not performant at first
- [ ] Copying of number not implemented yet
- [x] if a receipient address has no name, let's just leave it away ("unnamed contact") assumes an understanding of the "Contacts" concept already, which may not be the case.

# Checkout
- [x] arrow animation missing (also, arrow seems to be too thin...)
- [x] merchant logos should have padding to the border – also the nimiq hexagon
- [x] step 2: height of modal adapts to height of viewport, should stay the same

**Comment by sisou** [comment]
FYI, the screenshots here come from the regular `Nimiq Accounts Mgr & Keyguard Flows` Figma file, but are in the bottom page `__Feedback 26.03.18` (I'm guessing the `18` is a mistake and should be `19`).

**Comment by sisou** [comment]
First batch of UI style changes is in https://github.com/nimiq/keyguard-next/pull/269.

**Comment by sisou** [comment]
Completed. Issues for remaining important items have been created and assigned the correct repository.
