### ISSUE TITLE
Multilingualization: user-facing English text shouldn't be hardcoded

### ISSUE THREAD

**Issue by Smittyvb** [nimiq/hub#202]
User-facing English text should be pulled from a translatable file, instead of hardcoded, so that this can be multilingualized.

**Comment by sisou** [comment]
We were hoping to eventually integrate one of Vue's i18n plugins, such as https://kazupon.github.io/vue-i18n (tutorial: https://medium.freecodecamp.org/how-to-add-internationalization-to-a-vue-application-d9cfdcabb03b).

**Comment by danimoh** [comment]
Implemented via 9ac88a2af754445c78e1c355f41709ae4d14d5fe
