### ISSUE TITLE
Adding a selector for `tab-size` in the Keyguard Signature UI

### ISSUE THREAD

**Issue by MatthewDLudwig** [nimiq/hub#204]
Currently the Keyguard only accepts strings or Uint8Arrays as input, and I think this is fine.  But to help with ease of development, [NimiqWrapper](https://github.com/MatthewDLudwig/NimiqWrapper) allows the user to sign any javascript object.  This is done by using the `JSON.stringify(obj, NULL, "\t")` method, however this leads to the message being formatted with a lot of empty space due to the [default value of 8 spaces](https://www.w3schools.com/cssref/css3_pr_tab-size.asp) being used by all browsers (there is no way to change this in browser settings afaik, meaning the user has no say in how the message should look).

I propose adding a selector that allows setting (and remembering for future calls) the `tab-size` for the `textarea` (with id `message`) to either 2, 4, or 8 spaces.  This way the object can be displayed as the user wants (there is much debate for 2 vs 4, though no one I know likes 8), but the signature returned will be the same no matter which setting the user selects (since it's still tabs, no matter how it's displayed).

I envision a simple 3 switch button, where you can click on the number of spaces you want to be used.  Below is an image I threw together to show my idea:

![image](https://user-images.githubusercontent.com/6557206/55768588-74322080-5a4b-11e9-9e06-305820bb50e8.png)

**Comment by sisou** [comment]
Addition: the selector would only be displayed when a `\t` character is detected in the message string.
