### ISSUE TITLE
Add status updates to loading screens

### ISSUE THREAD

**Issue by sisou** [nimiq/hub#280]
Especially during checkout balance-loading and login address-detection the status text in the loader never changes.

We should come up with some nice statuses that we can loop through here to show to the user.

**Comment by sisou** [comment]
Suggestions for checkout balance loading:
- Connecting to network
- Contacting seed nodes
- Syncing consensus
- Updating balances

For transaction sending after checkout:
- Connecting to network
- Searching full peers
- Sending transaction
- Awaiting relay confirmation

For address discovery after login:
- Connecting to network
- Contacting peer nodes
- Scanning balances
- Requesting transaction histories
- Storing active addresses

**Comment by nibhar** [comment]
I think @danimoh added the number of retrieved accounts for the loader after login for Ledger Accounts.
