### ISSUE TITLE
Nimiq Hub bricked on adding new wallet to account

### ISSUE THREAD

**Issue by Eligioo** [nimiq/hub#309]
https://www.loom.com/share/9a19337091e345f793776d0c71d97437

How to reproduce:
When click on the `Select` button and right after press the `Escape` button on your keyboard.
You have to press the `Escape` button really fast after clicking the `Select` button.

**Comment by sisou** [comment]
I would not say this is an error that we should handle. Pressing ESC stops browser processes or loading of files/assets in the background, so not something that we can control.
