### ISSUE TITLE
User should be notified about redirect to import in ErrorHandler

### ISSUE THREAD

**Issue by danimoh** [nimiq/hub#313]
The `ErrorHandler` redirects to the Keyguard import flow on `KEY_NOT_FOUND` errors. Currently, this happens without notifying the user why this is happening.
For better UX be should let the user know why he's being redirected.

**Comment by sisou** [comment]
The Keyguard import UI displays a notice saying 'Please login to continue'. That is all that UX deemed necessary. I don't think another explanation is required.
