### ISSUE TITLE
Ledger icon is missing when a new address is added

### ISSUE THREAD

**Issue by tomkha** [nimiq/hub#316]
It's a very minor cosmetic issue - when you add a new Ledger address a small icon doesn't immediately appear there, above the identicon. Refreshing the page brings it back.

![ledger-address](https://user-images.githubusercontent.com/25764045/61597965-bad51080-ac1f-11e9-9a24-a3b025d776d2.jpg)

**Comment by sisou** [comment]
Fixed by https://github.com/nimiq/safe/commit/5e8c4ae4e430e9f9f13ecdfb21454513a7ccd03e.
