### ISSUE TITLE
Text overflow in claim cashlink screen

### ISSUE THREAD

**Issue by Bettelstab** [nimiq/hub#322]
Happens when message is too long.

![Screenshot from 2019-08-16 18-45-34](https://user-images.githubusercontent.com/3285528/63184016-b6511b80-c056-11e9-90e1-08dd96a050a0.png)

**Comment by sisou** [comment]
Thanks, @Bettelstab!

d9e6c1d8ad5fee3f0f1a0ac6b88f558ad53315ae should mitigate this.

**Comment by sisou** [comment]
Fixed by 2c1ee28a41e9628cfa1cb273a42a68eea814c3f1.
