### ISSUE TITLE
HubApi popup overlay does not cover scrollable pages

### ISSUE THREAD

**Issue by sisou** [nimiq/hub#357]
The new overlay added by #354 does not prevent scrolling when the page that is covered is taller than the viewport. It seems `overflow: hidden` must be added to the `html` tag (adding it to the `body` does not work), and then must be removed (or rather reset to what it was before) when the popup is closed.

**Comment by danimoh** [comment]
Scrolling of the overlay with the page has been fixed by making the popup `position: fixed`.
Do you think it's additionally desirable to make the page `overflow: hidden` to avoid scrolling of the page behind the overlay?

**Comment by sisou** [comment]
No, I think the current fix is sufficient. It would just look bad when the page jumps because the scrollbar is hidden.
