### ISSUE TITLE
I'm trying to use nimliq checkout but keep getting net::ERR_BLOCKED_BY_CLIENT

### ISSUE THREAD

**Issue by Th0rgal** [nimiq/hub#441]
Hi there,

I am trying to play with the checkout api (I would like to offer nimiq as a way to buy my programs). 
This is my code:
```cpp
<script type="module" crossorigin="anonymous">
    import HubApi from 'https://cdn.jsdelivr.net/npm/@nimiq/hub-api@latest/dist/standalone/HubApi.standalone.es.js';
    const hubApi = new HubApi('https://hub.nimiq.com');
    document.getElementById('checkoutBtn').addEventListener('click', function (event) {
        const options = {
            appName: 'Hub API Docs',
            recipient: 'NQ08 JYY6 7V0F EL7J CYNX RH78 TGD1 HP64 CSKG',
            value: 3.14 * 1e5, /* 3.14 NIM */
            // See more options in the table below
        };
        hubApi.checkout(options);
    });
</script>

<button id="checkoutBtn">Purchase</button>
```

I am using brave browser and when I click on the button, it never finish to load:
![2021-04-19-093059_1919x1079_escrotum](https://user-images.githubusercontent.com/41830259/115198208-192f6b80-a0f2-11eb-906a-94e81218db46.png)

It might be related to the brave adblocker but it would be a false positive. What should I do?

Sincerely,
Thomad

**Comment by sisou** [comment]
Hi Thomad!
Does the popup open and load correctly for you when you try the example on https://nimiq.github.io/hub/api-reference/checkout?

Did you try disabling the Brave shields on your localhost dev site, does it work then?

**Comment by Th0rgal** [comment]
> Hi Thomad!
> Does the popup open and load correctly for you when you try the example on https://nimiq.github.io/hub/api-reference/checkout?
> 
> Did you try disabling the Brave shields on your localhost dev site, does it work then?

This is actually the example I tried to follow in my code. Did I miss something?
I tried to disable brave shield (it is in fact disabled on the page) but I don't figure how to disable it on the popup (it seems the logo appears anyway), and this is pretty strange because I do not have these issues when using the nimiq wallet app for example.

**Comment by sisou** [comment]
There is likely a difference between blocking hub.nimiq.com and hub.nimiq-testnet.com. Please try opening `https://hub.nimiq-testnet.com` in your page. That should work.

Can you really not access the Brave shields when the popup is open? Can you not click on the Brave icon in the popup?

**Comment by Th0rgal** [comment]
> There is likely a difference between blocking hub.nimiq.com and hub.nimiq-testnet.com. Please try opening `https://hub.nimiq-testnet.com` in your page. That should work.
> 
> Can you really not access the Brave shields when the popup is open? Can you not click on the Brave icon in the popup?

Yes, I have been able to disable it (I restarted brave and it fixed the bug where I could not click on the brave logo). I have the same issue though (and I used ``https://hub.nimiq-testnet.com`` this time).
![image](https://user-images.githubusercontent.com/41830259/115297039-00f43680-a15c-11eb-8427-24d47d4bdb21.png)

**Comment by Th0rgal** [comment]
Is there a small example I could clone to try if I get the same error?

**Comment by sisou** [comment]
I sucessfully opened the Hub with your exact code from your initial post. But I served my file via `http://localhost`, not as the `file://` protocol. 
You need to serve the file that calls the Hub from localhost. You can for example use `serve` from Zeit (https://www.npmjs.com/package/serve). In the folder where your HTML file is, simply  run
```bash
serve
```
and you can access your file at http://localhost:5000. Also works with Brave.

_Please reopen the issue if this did not fix it for you._

**Comment by Th0rgal** [comment]
Great thank you very much!
