### ISSUE TITLE
Allow for recurring payments

### ISSUE THREAD

**Issue by code3z** [nimiq/hub#457]
Allow apps to request for recurring payments.

Maybe it could be done in the service worker? And the UI could be mostly reused from the request for normal payments, just with some information on how often the payment will happen.

**Comment by code3z** [comment]
I might be able to help with it, but I don't know where to start.

**Comment by sisou** [comment]
Automated recurring payments (subscriptions) are not supported by the blockchain, and thus cannot be realized only with the client-side Wallet.

It is currently only possible if an always-on service stores the pre-signed transactions and submits them at the correct time. And even then this does not guarantee that the NIM are still available in the Wallet when future transactions are sent. This is currently outside the scope of the Wallet/Hub.

**Comment by code3z** [comment]
So this should be requested on the blockchain section and not the hub? Or it is not possible?
