### ISSUE TITLE
How to integrate 'keyguard & hub' (Screenshots)

### ISSUE THREAD

**Issue by born8** [nimiq/hub#482]
sorry I'm a newbie, I'm trying to integrate 'keyguard & hub' over internet but having problems, anyone can help me

**Keyguard-Terminal**
![keyguard-terminal](https://user-images.githubusercontent.com/65473167/156281703-b9f5be3b-bf05-452d-be26-90b90c5f18c4.png)

**Hub-Terminal**
![hub-terminal](https://user-images.githubusercontent.com/65473167/156281809-4c38e67d-1aa4-4e5e-8394-04aeab95294c.png)

**on localhost:8080 via browser**
**(1)**
![localhost1](https://user-images.githubusercontent.com/65473167/156282038-4c934524-73e1-4283-b111-27410356a684.png)
**(2)**
![localhost2](https://user-images.githubusercontent.com/65473167/156282135-ec627f36-9972-4011-aba3-71431779e50f.png)

**Internet port 8080 (domain)**
![over-internet](https://user-images.githubusercontent.com/65473167/156282575-38fc95a5-5bec-4693-ad68-b7fa1ee19eb2.png)

Thanks

**Comment by sisou** [comment]
Hi @Born-8, thanks for finding this! This was indeed kind-of a bug, and I just pushed a fix to the `master` branch. Please pull the latest commits, run `yarn` or `npm install` again to get the new dependency version, and then try again. This time it should work in your local network.

**Comment by Born-8** [comment]
thanks bro :)
