### ISSUE TITLE
PoS: Checkout fails , Invalid Signature Proof

### ISSUE THREAD

**Issue by faberto** [nimiq/hub#522]
Following #517 

The Checkout is still broken.

`LogNative.js:46  [W 10:12:05] SignatureProof: Invalid SignatureProof - signature is invalid
LogNative.js:46  [W 10:12:05] Transaction: Invalid for sender Transaction{sender=B1p2zUnwRnYJoJ9GZ1KEI9JeX3w=, recipient=AAAAAAAAAAAAAAAAAAAAAAAAAAA=, value=314000, fee=0, validityStartHeight=9028530, networkId=1}`

https://jsfiddle.net/yg079fcr/

**Comment by sisou** [comment]
Fixed by 41f522df8e5d6b945d9783c254c75b5124b9e8c7. I was unablet to test it so far, as the popup always [crashes for me when sending the tx](https://github.com/nimiq/core-rs-albatross/issues/2007#issuecomment-1824789472).
